# This playbook intends to deploy immich container using podman
# version v1.124.2: https://github.com/immich-app/immich/releases/tag/v1.124.2
---
- hosts: cloud
  name: Deploy Immich using Podman
  tasks:
    - name: Install needed packages
      pacman:
        name:
          - podman
        state: present

    - name: Create the Quadlet directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
      - /etc/containers
      - /etc/containers/systemd

    - name: Copy the Quadlet files
      ansible.builtin.copy:
        src: "files/"
        dest: /etc/containers/systemd
        owner: root
        group: root
        mode: '0644'

    - name: Run daemon reload to make Quadlet create the service files
      ansible.builtin.systemd:
        daemon_reload: true

