- name: Upgrade PVE to latest version
  hosts: pve
  tasks:
    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
